export const ROLE_CAPABILITIES = {
  super_admin: [
    'platform.admin',
    'dashboard.view',
    'pos.open',
    'products.view',
    'products.manage',
    'inventory.view',
    'inventory.adjust',
    'customers.view',
    'customers.create',
    'customers.manage',
    'sales.view',
    'sales.void',
    'returns.view',
    'shifts.view',
    'shifts.manage',
    'reports.view',
    'users.view',
    'users.manage',
    'settings.manage',
    'mpesa.view',
  ],
  company_admin: [
    'dashboard.view',
    'pos.open',
    'products.view',
    'products.manage',
    'inventory.view',
    'inventory.adjust',
    'customers.view',
    'customers.create',
    'customers.manage',
    'sales.view',
    'sales.void',
    'returns.view',
    'shifts.view',
    'shifts.manage',
    'reports.view',
    'users.view',
    'users.manage',
    'settings.manage',
    'mpesa.view',
  ],
  branch_manager: [
    'dashboard.view',
    'pos.open',
    'products.view',
    'products.manage',
    'inventory.view',
    'inventory.adjust',
    'customers.view',
    'customers.create',
    'customers.manage',
    'sales.view',
    'sales.void',
    'returns.view',
    'shifts.view',
    'shifts.manage',
    'reports.view',
    'users.view',
    'mpesa.view',
  ],
  accountant: [
    'dashboard.view',
    'products.view',
    'products.manage',
    'inventory.view',
    'inventory.adjust',
    'customers.view',
    'sales.view',
    'returns.view',
    'reports.view',
    'finance.view',
    'mpesa.view',
  ],
  cashier: [
    'dashboard.view',
    'pos.open',
    'products.view',
    'inventory.view',
    'customers.view',
    'customers.create',
    'sales.view',
    'returns.view',
  ],
};

export const permissionToCapability = {
  view_products: 'products.view',
  manage_products: 'products.manage',
  view_inventory: 'inventory.view',
  adjust_stock: 'inventory.adjust',
  view_customers: 'customers.view',
  manage_customers: 'customers.manage',
  view_sales: 'sales.view',
  process_refund: 'returns.view',
  view_reports: 'reports.view',
  manage_users: 'users.manage',
  manage_settings: 'settings.manage',
  open_pos_session: 'pos.open',
};

export function capabilitiesForRole(role) {
  return new Set(ROLE_CAPABILITIES[role] ?? []);
}
